# Generated by Django 4.2.2 on 2023-06-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='filepath'),
        ),
    ]
