# Generated by Django 4.2.2 on 2023-06-20 10:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_relationship_user_currentaddress_user_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.filepath),
        ),
    ]
