# Generated by Django 4.2.2 on 2023-06-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='countrycode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
