from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.UserRegister),
    path('', views.HomePage),
    path('services/', views.OurServices),
    path('servicefilter/<int:id>/', views.FilterByCategory, name="puja"),
    path('pujadetail/<int:id>/', views.ViewPujaDetail, name='pujadetail'),    
    path('pujaslot/<int:id>/', views.AddPoojaSlot, name="pujaslot"),
    path('viewpujadiscrip/<int:id>/', views.ViewPujadescription, name="viewpuja"),
    path('products/', views.OurProducts),
    path('productfilter/<int:id>/', views.FilterProductByCategory, name="prod"),
    path('horoscope/<int:id>/', views.FilterHoroscopeByCategory, name='horoscope'),
    path('proddetail/<int:id>/', views.ViewProductDetail, name='proddetail'),
    path('addtocart/<int:id>/', views.AddToCart, name="addcart"),
    path('showcart/', views.ViewCartProduct, name="payid"),
    path('viewproddiscrip/<int:id>/', views.ViewProductdescription, name="viewprod"),
    path('checkout/', views.Checkout),
    path('askquestion/', views.QusAndAnswerView),
    path('askquestionpay/', views.QusAndAnswerViewPayment),
    path('profile/', views.ShowProfileDetail),
    path('editprofile/<int:id>/', views.EditProfileView, name='editpro'),
    path('pujaslot/', views.ViewPujaSlotBooking),
    path('allblogs/', views.DailyBlosView),
    path('friendfunction/', views.FamilyFriendCreate),
    path('getfriendfunction/', views.AddFriendView),
    path('editfriendfunctionpro/<int:id>/', views.EditFriendProfileView, name='editfamilypro'),    
    path('delfriendfunctionpro/<int:id>/', views.DeleteFriendProfile, name='delfamilypro'),
    path('orderlist/', views.GetOrderView),
    path('customersupport/', views.SendCustomerSupport),
    # path('horoscope/', views.HoroscopeView),
    path('faqreply/', views.ShowFAQReply),
    path('prodorder/', views.ShowOrderlist),
    path('pujaorder/', views.ShowPojaSlot),
    path('faqpay/', views.ShowFaqPayment),
    path('deletecart/<int:id>/', views.DeleteCart, name='delcart'),
    path('deletepuja/<int:id>/', views.DeletePoja, name='delpuja'),
    path('addresstoorder/', views.OrderPlaceAddres),
    path('addwallet/', views.AddWalletAmount, name="wallet"),
    path('paymentadmin/',views.PaymentByRazorpay),
    path('paywithwallet/',views.PayWithWallet),
    path('paywithwalletforpuja/',views.PayWithWalletforPuja),
    path('paywithwalletforqa/',views.PayWithWalletforQA),
    path('checkoutforqa/',views.CheckoutforQA),
    path('checkoutforpuja/',views.CheckoutforPuja),
    path('mailpass/',views.SendMailToPassword,name='mailpass'),
    path('changeuserpassword/<int:id>/<str:username>/',views.UserForgotPassword, name='changepass1'),
    
]