# Generated by Django 4.2.2 on 2023-06-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_pooja_dateofpuja'),
        ('userapp', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pujaslotbooking',
            name='dateofpuja',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='pujaslotbooking',
            name='pujaslot',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminapp.poojaslot'),
            preserve_default=False,
        ),
    ]
