# Generated by Django 4.2.2 on 2023-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_pujaslotbooking_dateofpuja_pujaslotbooking_pujaslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
