# Generated by Django 4.2.2 on 2023-06-08 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfPooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=200, null=True)),
                ('prodpicture', models.ImageField(blank=True, null=True, upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='CreatePandit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=150, null=True)),
                ('languages', models.CharField(max_length=150, null=True)),
                ('expertise_in', models.CharField(max_length=150, null=True)),
                ('about', models.CharField(max_length=300, null=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('panditpicture', models.ImageField(blank=True, null=True, upload_to='panditimg')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=200, null=True)),
                ('prodpicture', models.ImageField(blank=True, null=True, upload_to='productimg')),
                ('discription', models.CharField(max_length=500, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('pojapicture', models.ImageField(blank=True, null=True, upload_to='productimg')),
                ('discription', models.CharField(max_length=250, null=True)),
                ('needofpuja', models.CharField(max_length=450, null=True)),
                ('advantages', models.CharField(max_length=500, null=True)),
                ('pujasamagri', models.CharField(max_length=400, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('offers', models.CharField(max_length=200, null=True)),
                ('faq', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.categoryofpooja')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('order_price', models.CharField(max_length=200, null=True)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
