# Generated by Django 4.2.2 on 2023-06-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_horoscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='offers',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
