# Generated by Django 4.2.2 on 2023-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_pooja_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catprod', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
