# Generated by Django 4.2.2 on 2023-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_horoscopecategory_remove_horoscope_horscopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopecategory',
            name='horoscopeimg',
            field=models.ImageField(blank=True, null=True, upload_to='horoscop'),
        ),
    ]
