# Generated by Django 4.2.2 on 2023-06-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_horoscopecategory_horoscopeimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='horscopname',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminapp.horoscopecategory'),
            preserve_default=False,
        ),
    ]
