# Generated by Django 4.2.2 on 2023-06-12 17:32

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_products_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryofpooja',
            name='prodpicture',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.filepath),
        ),
    ]
