# Generated by Django 4.2.2 on 2023-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_categoryofpooja_prodpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
