# Generated by Django 4.2.2 on 2023-06-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_categoryoffaq_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='qusandanswer',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminapp.categoryoffaq'),
            preserve_default=False,
        ),
    ]
