# Generated by Django 4.2.2 on 2023-06-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_qusandanswer_qusprice_qusandanswer_answertime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qusandanswer',
            name='ask_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
