# Generated by Django 4.2.2 on 2023-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_order_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
