# Generated by Django 4.2.2 on 2023-06-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_alter_order_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slottime', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
