# Generated by Django 4.2.2 on 2023-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_pooja_pujaslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
