# Generated by Django 4.2.2 on 2023-06-14 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0022_pooja_dateofpuja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=200, null=True)),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('quantity', models.CharField(max_length=12, null=True)),
                ('order_price', models.CharField(max_length=200, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
