# Generated by Django 4.2.2 on 2023-06-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_poojaorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poojaorder',
            old_name='productid',
            new_name='pujaid',
        ),
    ]
