# Generated by Django 4.1.4 on 2023-06-15 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_rename_productid_poojaorder_pujaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=200, null=True)),
                ('blogimg', models.FileField(blank=True, null=True, upload_to='blog')),
                ('discription', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 16, 18, 0, 36, 12428), max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='pujaslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.poojaslot'),
        ),
    ]
