# Generated by Django 4.2.2 on 2023-06-16 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_dailyblogs_alter_pooja_dateofpuja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 17, 6, 7, 55, 391150), max_length=12, null=True),
        ),
    ]
