# Generated by Django 4.2.2 on 2023-06-18 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_alter_pooja_dateofpuja_customersupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 19, 14, 51, 59, 626773), max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='poojaorder',
            name='pujaid',
            field=models.JSONField(default=list, null=True),
        ),
    ]
