# Generated by Django 4.2.2 on 2023-06-18 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_alter_order_productid_alter_pooja_dateofpuja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 19, 16, 28, 38, 301913), max_length=12, null=True),
        ),
    ]
