# Generated by Django 4.2.2 on 2023-06-21 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0034_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryofpooja',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryofproduct',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pooja',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 11, 44, 48, 924111), max_length=12, null=True),
        ),
    ]
