# Generated by Django 4.2.2 on 2023-06-21 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0035_categoryofpooja_active_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryofpooja',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoryofproduct',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 11, 51, 51, 747548), max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
