# Generated by Django 4.2.2 on 2023-06-21 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0036_alter_categoryofpooja_active_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 11, 56, 35, 146533), max_length=12, null=True),
        ),
    ]
