# Generated by Django 4.2.2 on 2023-06-21 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0038_alter_pooja_dateofpuja_orderplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 13, 39, 48, 659277), max_length=12, null=True),
        ),
    ]
