# Generated by Django 4.2.2 on 2023-06-21 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 14, 23, 11, 675904), max_length=12, null=True),
        ),
    ]
