# Generated by Django 4.2.2 on 2023-06-21 20:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0040_order_address_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPlace',
            new_name='OrderPlaceAddress',
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 22, 20, 44, 35, 18693), max_length=12, null=True),
        ),
    ]
