# Generated by Django 4.2.2 on 2023-06-22 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_rename_orderplace_orderplaceaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qusandanswer',
            name='friend',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 23, 10, 23, 11, 718089), max_length=12, null=True),
        ),
    ]
