# Generated by Django 4.2.2 on 2023-06-23 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0042_qusandanswer_friend_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 24, 7, 34, 41, 313172), max_length=12, null=True),
        ),
    ]
