# Generated by Django 4.2.2 on 2023-06-23 12:11

import adminapp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0044_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryofpooja',
            name='prodpicture',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.filepath3),
        ),
        migrations.AlterField(
            model_name='createpandit',
            name='panditpicture',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.filepath),
        ),
        migrations.AlterField(
            model_name='dailyblogs',
            name='blogimg',
            field=models.FileField(blank=True, null=True, upload_to=adminapp.models.filepath6),
        ),
        migrations.AlterField(
            model_name='horoscopecategory',
            name='horoscopeimg',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.filepath5),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 24, 12, 11, 15, 128208), max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='pojapicture',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.filepath4),
        ),
        migrations.AlterField(
            model_name='products',
            name='prodpicture',
            field=models.ImageField(blank=True, null=True, upload_to=adminapp.models.filepath2),
        ),
    ]
