# Generated by Django 4.2.2 on 2023-06-24 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0045_alter_categoryofpooja_prodpicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 25, 10, 41, 20, 970129), max_length=12, null=True),
        ),
    ]
