# Generated by Django 4.2.2 on 2023-06-25 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0046_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 26, 18, 3, 55, 909523), max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='pujaslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.poojaslot'),
        ),
    ]
