# Generated by Django 4.2.2 on 2023-06-26 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_alter_pooja_dateofpuja_alter_pooja_pujaslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offerprice',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 27, 7, 30, 15, 145121), max_length=12, null=True),
        ),
    ]
