# Generated by Django 4.2.2 on 2023-06-26 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_products_offerprice_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooja',
            name='offerprice',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 27, 7, 53, 50, 721789), max_length=12, null=True),
        ),
    ]
