# Generated by Django 4.2.2 on 2023-06-26 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0049_pooja_offerprice_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 6, 27, 11, 47, 10, 622347), max_length=12, null=True),
        ),
    ]
