# Generated by Django 4.2.2 on 2023-06-30 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0050_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 7, 1, 8, 37, 3, 136876), max_length=12, null=True),
        ),
    ]
