# Generated by Django 4.2.2 on 2023-07-04 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0052_walletadd_poojaorder_address_alter_pooja_dateofpuja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 7, 5, 13, 19, 19, 481000), max_length=12, null=True),
        ),
    ]
