# Generated by Django 4.2.2 on 2023-07-10 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0055_alter_pooja_dateofpuja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poojaorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='poojaorder',
            name='bookeddate',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pooja',
            name='dateofpuja',
            field=models.CharField(default=datetime.datetime(2023, 7, 11, 7, 54, 27, 374), max_length=12, null=True),
        ),
    ]
